on:
  push:
    branches: [ main, master, devel ]
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  pull_request:
    branches: '**'
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest' ]
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gdal-bin libgdal-dev libgeos-dev libproj-dev \
          libsqlite3-dev libtbb-dev cmake build-essential

    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y gdal proj geos cmake

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel numpy pybind11

    - name: Configure pybind11 path
      shell: bash
      run: |
        PYBIND11_DIR=$(python -c "import pybind11; print(pybind11.get_cmake_dir())")
        echo "pybind11_DIR=$PYBIND11_DIR" >> $GITHUB_ENV

    - name: Build Python extension
      shell: bash
      working-directory: python
      run: |
        python setup.py build_ext --inplace -v
        echo "Built modules:"
        find . -name "*.so" | head -20

    - name: Run tests
      shell: bash
      working-directory: python
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python -c "import pylasr; print('pylasr imported successfully')"
        python tests/run_tests.py

    - name: Quick smoke test
      shell: bash
      working-directory: python
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python tests/run_tests.py --quick