on:
  push:
    branches: [ main, master, devel ]
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  pull_request:
    branches: '**'
    paths:
      - 'python/**'
      - 'src/**'
      - '.github/workflows/pylasr.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: ['3.11', '3.12', '3.13']
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gdal-bin \
          libgdal-dev \
          libgeos-dev \
          libproj-dev \
          libsqlite3-dev \
          libtbb-dev \
          cmake \
          build-essential

    - name: Install system dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install libomp gdal geos proj sqlite3 tbb cmake

    - name: Install Python dependencies on Ubuntu/macOS
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel numpy pybind11

    - name: Configure pybind11 path on Ubuntu/macOS
      run: |
        PYBIND11_DIR=$(python -c "import pybind11; print(pybind11.get_cmake_dir())")
        echo "pybind11_DIR=$PYBIND11_DIR" >> $GITHUB_ENV

    - name: Build extension on Ubuntu/macOS
      run: |
        cd python
        python setup.py build_ext --inplace -vvv
        find . -name "*.so" | head -20

    - name: Run tests on Ubuntu/macOS
      working-directory: python
      run: |
        # Add current directory to Python path to find the built module
        export PYTHONPATH=$PWD:$PYTHONPATH
        echo "PYTHONPATH=$PYTHONPATH"
        
        # Try importing pylasr directly first
        python -c "import sys; print('Python path:', sys.path); import pylasr; print('pylasr imported successfully')" || echo "Failed to import pylasr"
        
        # Run the actual tests
        python tests/run_tests.py

    - name: Run quick smoke test
      working-directory: python
      run: |
        # Add current directory to Python path to find the built module
        export PYTHONPATH=$PWD:$PYTHONPATH
        python tests/run_tests.py --quick